name: happy_hour_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.17.0
  responsive_framework: ^0.2.0
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.1.1+1
  toggle_switch: ^2.0.1
  google_maps_flutter: ^2.1.8
  flutter_credit_card: ^3.0.1
  carousel_pro: ^1.0.0
  card_swiper: ^2.0.4
  get_storage: ^2.0.3
  image_picker: ^0.8.5+3
  flutter_rating_bar: ^4.0.1
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.2
  firebase_storage: ^10.3.4
  fluttertoast: ^8.0.9
  firebase_auth: ^3.6.2
  flutterfire_ui: ^0.4.3+8
  cached_network_image: ^3.2.1
  location: ^4.4.0
  url_launcher: ^6.1.5
  multiselect: ^0.0.7
  geolocator: ^7.0.1
  geocoding: ^2.0.5
  photo_view: ^0.14.0
  flutter_typeahead: ^4.1.0
  geoflutterfire: ^3.0.3
  dio: ^4.0.6
  google_maps_place_picker: ^2.1.0-nullsafety.3
  multi_select_flutter: ^4.1.2
  photo_gallery: ^1.1.1
  flutter_spinkit: ^5.1.0
  connectivity: ^3.0.6
  # flutter_stripe: ^2.1.0
  flutter_config: ^2.0.0
  cloud_functions: ^3.3.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - .env
  #   - images/a_dot_ham.jpeg

